#!/usr/bin/env python3
"""Aggregate runs/index.jsonl into RESULTS.md (the project leaderboard)."""
from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from slp.benchmarks import registry
from slp.tracking import REPO, load_index

PUBLISHED = {
    # instance -> (best published gate count, reference)
    "aes_mixcolumns": (88, "eprint 2026/1481"),
}
REPRO_TARGETS = {
    # (instance, method) -> published value our implementation must match
    ("aes_mixcolumns", "paar1"): 108,
    ("aes_mixcolumns", "bp"): 97,
}


def main() -> int:
    rows = load_index()
    if not rows:
        print("no runs recorded yet")
        return 1

    by_inst_method: dict[tuple[str, str], dict] = {}
    for r in rows:
        key = (r["instance"], r["method"])
        if key not in by_inst_method or r["gates"] < by_inst_method[key]["gates"]:
            by_inst_method[key] = r

    instances = sorted({k[0] for k in by_inst_method})
    methods = sorted({k[1] for k in by_inst_method})

    out = ["# Results", "",
           "Auto-generated by `scripts/aggregate.py` from `runs/index.jsonl`.",
           "Every number below is a **verified** gate count: the program was re-executed",
           "from scratch by `slp.instance.verify` before being recorded.", ""]

    out += ["## Reproduction of published baselines", "",
            "| instance | method | ours | published | status |",
            "|---|---|---:|---:|---|"]
    for (inst, method), published in sorted(REPRO_TARGETS.items()):
        got = by_inst_method.get((inst, method))
        if got is None:
            out.append(f"| {inst} | {method} | - | {published} | not run |")
            continue
        status = "match" if got["gates"] == published else (
            "BETTER" if got["gates"] < published else "MISMATCH")
        out.append(f"| {inst} | {method} | {got['gates']} | {published} | {status} |")
    out.append("")

    out += ["## Leaderboard", "",
            "| instance | n | naive | " + " | ".join(methods) + " | best | published | gap |",
            "|---|---:|---:|" + "---:|" * (len(methods) + 3)]
    for inst in instances:
        cells = []
        best = None
        n = naive = None
        for m in methods:
            r = by_inst_method.get((inst, m))
            if r is None:
                cells.append("-")
            else:
                cells.append(str(r["gates"]))
                n, naive = r.get("n_inputs"), r["naive"]
                best = r["gates"] if best is None else min(best, r["gates"])
        pub, ref = PUBLISHED.get(inst, (None, None))
        gap = "" if pub is None or best is None else f"{best - pub:+d}"
        out.append(f"| {inst} | {n or ''} | {naive or ''} | " + " | ".join(cells) +
                   f" | {best if best is not None else '-'} | "
                   f"{pub if pub is not None else '-'} | {gap} |")
    out.append("")

    counts = defaultdict(int)
    for r in rows:
        counts[r["method"]] += 1
    out += ["## Provenance", "",
            f"- recorded results: **{len(rows)}**",
            f"- distinct instances: **{len(instances)}**",
            "- results per method: " + ", ".join(f"`{k}`={v}" for k, v in sorted(counts.items())),
            f"- dirty-tree results: **{sum(1 for r in rows if r.get('dirty'))}** "
            "(these must not be used for any published claim)", ""]

    (REPO / "RESULTS.md").write_text("\n".join(out))
    print("\n".join(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
